######################
### APPLICATIONS   ###
######################

bindd = $mainMod SHIFT, T, Theme Switcher, exec, ~/.local/bin/theme-switcher.sh
bindd = $mainMod SHIFT, W, Wallpaper Picker, exec, ~/.local/bin/wallpaper-switcher.sh pick
bindd = $mainMod ALT, W, Next Wallpaper, exec, ~/.local/bin/wallpaper-switcher.sh next
bindd = $mainMod, T, Terminal, exec, $terminal
bindd = $mainMod, B, Browser, exec, $browser
bindd = $mainMod, O, Notes, exec, $notes
bindd = $mainMod, S, Android Studio, exec, $androidstudio
bindd = $mainMod, F, File Manager, exec, $fileManager
bindd = $mainMod, A, App Launcher, exec, $menu
bindd = $mainMod, E, Emoji Picker, exec, jome -d | wl-copy
bindd = SUPER, V, Clipboard Manager, exec, cliphist list | rofi --show dmenu | cliphist decode | wl-copy
bindd = $mainMod, M, Color Picker, exec, $colorPicker | wl-copy
