######################
### APPLICATIONS   ###
######################

# Theme switcher
bind = $mainMod SHIFT, T, exec, ~/.local/bin/theme-switcher.sh
bind = $mainMod, T, exec, $terminal
bind = $mainMod, B, exec, $browser
bind = $mainMod, O, exec, $notes
bind = $mainMod, S, exec, $androidstudio
bind = $mainMod, F, exec, $fileManager
bind = $mainMod, A, exec, $menu

# Emoji picker
bind = $mainMod, E, exec, jome -d | wl-copy

# Clipboard manager
bind = SUPER, V, exec, cliphist list | rofi --show dmenu | cliphist decode | wl-copy

# Colour Picker
bind = $mainMod, M, exec, $colorPicker | wl-copy
