####################
### KEYBINDINGS  ###
####################

# See https://wiki.hyprland.org/Configuring/Binds/ for more

# Source all binding categories
source = ~/.config/hypr/bindings/applications.conf
source = ~/.config/hypr/bindings/window-management.conf
source = ~/.config/hypr/bindings/workspaces.conf
source = ~/.config/hypr/bindings/media.conf
source = ~/.config/hypr/bindings/screenshot.conf
source = ~/.config/hypr/bindings/recording.conf
source = ~/.config/hypr/bindings/system.conf
