####################################
### VOLUME AND MEDIA CONTROLS    ###
####################################

# Volume controls
bindd = , XF86AudioRaiseVolume, Volume Up, exec, wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+ && $HOME/.local/bin/volume-notify.sh
bindd = , XF86AudioLowerVolume, Volume Down, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-  && $HOME/.local/bin/volume-notify.sh
bindd = , XF86AudioMicMute, Toggle Mic Mute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindd = , XF86AudioMute, Toggle Mute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle &&  $HOME/.local/bin/volume-notify.sh muted

# Media player controls
bindd = , XF86AudioPlay, Play/Pause, exec, playerctl play-pause
bindd = , XF86AudioPause, Play/Pause, exec, playerctl play-pause
bindd = , XF86AudioNext, Next Track, exec, playerctl next
bindd = , XF86AudioPrev, Previous Track, exec, playerctl previous

# Screen brightness
bindd = , XF86MonBrightnessUp, Brightness Up, exec, brightnessctl s +5% && "$HOME/.local/bin/brightness-notify.sh"
bindd = , XF86MonBrightnessDown, Brightness Down, exec, brightnessctl s 5%- && "$HOME/.local/bin/brightness-notify.sh"

# Keyboard backlight
bindd = , XF86KbdBrightnessUp, Keyboard Backlight Up, exec, $HOME/.local/bin/keyboard-brightness.sh up
bindd = , XF86KbdBrightnessDown, Keyboard Backlight Down, exec, $HOME/.local/bin/keyboard-brightness.sh down
