####################################
### VOLUME AND MEDIA CONTROLS    ###
####################################

# Volume controls
bind = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+ && $HOME/.local/bin/volume-notify.sh
bind = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-  && $HOME/.local/bin/volume-notify.sh
bind = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle 
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle &&  $HOME/.local/bin/volume-notify.sh muted

# Media player controls
bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioPause, exec, playerctl play-pause
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPrev, exec, playerctl previous

# Screen brightness
bind = , XF86MonBrightnessUp, exec, brightnessctl s +5% && "$HOME/.local/bin/brightness-notify.sh"
bind = , XF86MonBrightnessDown, exec, brightnessctl s 5%- && "$HOME/.local/bin/brightness-notify.sh"

# Keyboard backlight
bind = , XF86KbdBrightnessUp, exec, $HOME/.local/bin/keyboard-brightness.sh up
bind = , XF86KbdBrightnessDown, exec, $HOME/.local/bin/keyboard-brightness.sh down
