############################
### SCREEN RECORDING     ###
############################

# Screen Recording (wf-recorder / wl-screenrec)

# Record region with MIC audio
bind = $mainMod, R, exec, ~/.local/bin/screen-record.sh region mic

# Record output (full screen) with MIC audio
bind = $mainMod SHIFT, R, exec, ~/.local/bin/screen-record.sh output mic

# Record region with INTERNAL (system) audio
bind = $mainMod ALT, R, exec, ~/.local/bin/screen-record.sh region internal

# Record output (full screen) with INTERNAL (system) audio
bind = $mainMod SHIFT ALT, R, exec, ~/.local/bin/screen-record.sh output internal

# Record region WITHOUT audio
bind = $mainMod CTRL, R, exec, ~/.local/bin/screen-record.sh region none

# Record output WITHOUT audio
bind = $mainMod CTRL SHIFT, R, exec, ~/.local/bin/screen-record.sh output none
