############################
### SCREEN RECORDING     ###
############################

bindd = $mainMod, R, Record Region (Mic), exec, ~/.local/bin/screen-record.sh region mic
bindd = $mainMod SHIFT, R, Record Screen (Mic), exec, ~/.local/bin/screen-record.sh output mic
bindd = $mainMod ALT, R, Record Region (System Audio), exec, ~/.local/bin/screen-record.sh region internal
bindd = $mainMod SHIFT ALT, R, Record Screen (System Audio), exec, ~/.local/bin/screen-record.sh output internal
bindd = $mainMod CTRL, R, Record Region (No Audio), exec, ~/.local/bin/screen-record.sh region none
bindd = $mainMod CTRL SHIFT, R, Record Screen (No Audio), exec, ~/.local/bin/screen-record.sh output none
