####################
### SCREENSHOT   ###
####################

# Screenshot bindings
# Add --cursor flag to include cursor also, --freeze flag to freeze before selection
bind = , Print, exec, $HOME/.local/bin/screenshot.sh monitor
bind = SUPER, Print, exec, $HOME/.local/bin/screenshot.sh window
bind = SUPER ALT, Print, exec, $HOME/.local/bin/screenshot.sh region
bind = SUPER CTRL, Print, exec, $HOME/.local/bin/screenshot.sh clipboard
