####################
### SCREENSHOT   ###
####################

bindd = , Print, Screenshot Monitor, exec, $HOME/.local/bin/screenshot.sh monitor
bindd = SUPER, Print, Screenshot Window, exec, $HOME/.local/bin/screenshot.sh window
bindd = SUPER ALT, Print, Screenshot Region, exec, $HOME/.local/bin/screenshot.sh region
bindd = SUPER CTRL, Print, Screenshot to Clipboard, exec, $HOME/.local/bin/screenshot.sh clipboard
