######################
### SYSTEM CONTROL ###
######################

# System controls
bind = $mainMod, X, exit,
bind = SUPER SHIFT, L, exec, hyprlock
bind = SUPER, ESCAPE, exec, $powermenu
bind = Ctrl, Escape, exec, killall waybar || waybar # toggle waybar

# CPU mode toggle
bind = $mainMod, P, exec, ~/.local/bin/toggle_cpu_mode.sh

# Monitor mirroring
bind = $mainMod SHIFT, M, exec, ~/.local/bin/monitor-mirror-toggle.sh
bind = $mainMod CTRL, V, exec, ~/.local/bin/virtual-mirror-toggle.sh
