######################
### SYSTEM CONTROL ###
######################

bindd = $mainMod, X, Exit Hyprland, exit,
bindd = SUPER SHIFT, L, Lock Screen, exec, hyprlock
bindd = SUPER, ESCAPE, Power Menu, exec, $powermenu
bindd = Ctrl, Escape, Toggle Waybar, exec, killall waybar || uwsm app -- waybar
bindd = $mainMod SHIFT, M, Toggle Monitor Mirror, exec, ~/.local/bin/monitor-mirror-toggle.sh
bindd = $mainMod CTRL, V, Toggle Virtual Mirror, exec, ~/.local/bin/virtual-mirror-toggle.sh
bindd = $mainMod, N, Toggle Nightlight, exec, ~/.local/bin/toggle-nightlight.sh
bindd = $mainMod SHIFT, I, Toggle Idle Prevention, exec, ~/.local/bin/toggle-idle.sh
bindd = $mainMod, D, Dismiss Notifications, exec, ~/.local/bin/notification-dismiss.sh
bindd = $mainMod, F10, Switch Audio Output, exec, ~/.local/bin/audio-switch.sh
bindd = $mainMod, slash, Show Keybindings, exec, ~/.local/bin/show-keybindings.sh
