###########################
### WINDOW MANAGEMENT   ###
###########################

bindd = $mainMod, Q, Close Window, killactive,
bindd = $mainMod, W, Toggle Floating, togglefloating,
# bindd = $mainMod SHIFT, J, Toggle Split, togglesplit,

# Move focus (vim-style)
bindd = $mainMod, H, Focus Left, movefocus, l
bindd = $mainMod, L, Focus Right, movefocus, r
bindd = $mainMod, K, Focus Up, movefocus, u
bindd = $mainMod, J, Focus Down, movefocus, d

# Resize windows
binded = $mainMod+Shift, Right, Resize Right, resizeactive, 30 0
binded = $mainMod+Shift, Left, Resize Left, resizeactive, -30 0
binded = $mainMod+Shift, Up, Resize Up, resizeactive, 0 -30
binded = $mainMod+Shift, Down, Resize Down, resizeactive, 0 30

# Move/resize with mouse
bindmd = $mainMod, mouse:272, Move Window, movewindow
bindmd = $mainMod, mouse:273, Resize Window, resizewindow
