###########################
### WINDOW MANAGEMENT   ###
###########################

# Window actions
bind = $mainMod, Q, killactive,
bind = $mainMod, W, togglefloating,
bind = $mainMod SHIFT, J, togglesplit, # dwindle

# Move focus with mainMod + hjkl (vim-style)
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Resize windows with arrow keys
binde = $mainMod+Shift, Right, resizeactive, 30 0
binde = $mainMod+Shift, Left, resizeactive, -30 0
binde = $mainMod+Shift, Up, resizeactive, 0 -30
binde = $mainMod+Shift, Down, resizeactive, 0 30

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
