accent = "#1A76C9"
cursor = "#ffffff"
foreground = "#F9F8FE"
background = "#010a1a"
selection_foreground = "#010a1a"
selection_background = "#ffb703"

color0 = "#051f42"
color1 = "#ff5d5d"
color2 = "#1F7DD3"
color3 = "#ffcc00"
color4 = "#1e6091"
color5 = "#9d4edd"
color6 = "#1E4BC3"
color7 = "#1A76C9"
color8 = "#184e77"
color9 = "#ff5d5d"
color10 = "#0F50A5"
color11 = "#ffb703"
color12 = "#1a759f"
color13 = "#5E6FDD"
color14 = "#2A93DD"
color15 = "#ffffff"
