# Emulator
windowrule = float on, match:class ^(Emulator)$, match:title ^(Emulator)$
windowrule = center on, match:class ^(Emulator)$, match:title ^(Emulator)$

# Android Emulator
windowrule = float on, match:class ^(Android Emulator)$, match:title ^(Android Emulator.*)$
windowrule = center on, match:class ^(Android Emulator)$, match:title ^(Android Emulator.*)$
