# App Specific Tweaks

source = ~/.config/hypr/windows/steam.conf
source = ~/.config/hypr/windows/browser.conf
source = ~/.config/hypr/windows/terminal.conf
source = ~/.config/hypr/windows/webcam.conf
source = ~/.config/hypr/windows/system.conf
source = ~/.config/hypr/windows/viewer.conf
source = ~/.config/hypr/windows/geforce.conf
source = ~/.config/hypr/windows/jetbrains.conf
source = ~/.config/hypr/windows/qemu.conf
