# App Specific Tweaks

source = ~/.config/hypr/windows/steam.conf
source = ~/.config/hypr/windows/browser.conf
source = ~/.config/hypr/windows/terminal.conf
source = ~/.config/hypr/windows/webcam.conf
source = ~/.config/hypr/windows/system.conf
source = ~/.config/hypr/windows/viewer.conf
source = ~/.config/hypr/windows/geforce.conf
source = ~/.config/hypr/windows/jetbrains.conf
source = ~/.config/hypr/windows/qemu.conf
source = ~/.config/hypr/windows/emulator.conf
source = ~/.config/hypr/windows/pip.conf
source = ~/.config/hypr/windows/moonlight.conf
source = ~/.config/hypr/windows/retroarch.conf
source = ~/.config/hypr/windows/davinci-resolve.conf
source = ~/.config/hypr/windows/localsend.conf
source = ~/.config/hypr/windows/telegram.conf
source = ~/.config/hypr/windows/hyprshot.conf
