
###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = ghostty 
$fileManager = nautilus
$menu = ~/.config/rofi/launcher.sh 
$browser = firefox --enable-features=UseOzonePlatform --ozone-platform=wayland
$notes = obsidian
$colorPicker = hyprpicker
$androidstudio = android-studio
