#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

# NOTE: Cursor, Wayland, and NVIDIA env vars are set in ~/.config/uwsm/env
# NVIDIA vars are auto-detected and appended by install.sh

xwayland {
  force_zero_scaling = true
}

# Use XCompose file
env = XCOMPOSEFILE,~/.XCompose

# Don't show update on first launch
ecosystem {
  no_update_news = true
}
