accent = "#ffb703"
cursor = "#ffffff"
foreground = "#d9ed92"
background = "#010a1a"
selection_foreground = "#010a1a"
selection_background = "#ffb703"

color0 = "#051f42"
color1 = "#ff4d6d"
color2 = "#52b69a"
color3 = "#ffcc00"
color4 = "#1e6091"
color5 = "#9d4edd"
color6 = "#34a0a4"
color7 = "#d9ed92"
color8 = "#184e77"
color9 = "#ff5d5d"
color10 = "#76c893"
color11 = "#ffb703"
color12 = "#1a759f"
color13 = "#c77dff"
color14 = "#52b69a"
color15 = "#ffffff"
